import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] })
const p = await (await b.newContext()).newPage()
await p.goto('http://localhost:3400/login')
await p.fill('#username', 'saurabh'); await p.fill('#password', 'change-me-now')
await p.click('button[type=submit]'); await p.waitForURL('**/admin**')
await p.goto('http://localhost:3400/admin')
const h = await p.$eval('a[href^="/admin/t/"]', (a) => a.getAttribute('href'))
console.log(h.split('/admin/t/')[1])
await b.close()
